import asyncio
import time
from pprint import pprint

from agently import TriggerFlow

from _shared_model import configure_model, print_model_provider


TASK_DURATIONS = {"t1": 0.8, "t2": 0.5, "t3": 0.7, "t4": 0.2, "t5": 0.2}


def decompose_task(task: str) -> list[dict]:
    from agently import Agently

    response = (
        Agently.create_agent()
        .input(task)
        .instruct([
            "Decompose the task into exactly five concrete implementation tasks.",
            "Use ids t1, t2, t3, t4, and t5 exactly.",
            "Make t1, t2, and t3 independent with empty depends_on lists.",
            "Make t4 depend on t1.",
            "Make t5 depend on t2, t3, and t4.",
        ])
        .output({
            "tasks": [{
                "id": ("str", "task id"),
                "title": ("str", "short task title"),
                "description": ("str", "what to do"),
                "depends_on": (["str"], "task ids that must finish first"),
            }],
            "summary": ("str", "decomposition summary"),
        })
        .get_response()
    )
    return response.get_data(ensure_keys=["tasks"])["tasks"]


def split_by_dependency(tasks: list[dict]) -> tuple[list[dict], list[dict]]:
    independent = [task for task in tasks if not task.get("depends_on")]
    dependent = [task for task in tasks if task.get("depends_on")]
    return independent, dependent


def build_parallel_executor():
    flow = TriggerFlow(name="cookbook-todo-concurrent-model")

    async def execute_one(data):
        task = data.input
        await asyncio.sleep(TASK_DURATIONS.get(task["id"], 0.6))
        return {
            "id": task["id"],
            "title": task["title"],
            "result": f"{task['title']} done",
        }

    async def collect(data):
        await data.async_set_state("results", data.input)

    flow.for_each(concurrency=3).to(execute_one).end_for_each().to(collect)
    return flow


async def run_parallel(tasks: list[dict]) -> tuple[float, list[dict]]:
    flow = build_parallel_executor()
    started = time.perf_counter()
    execution = flow.create_execution(auto_close_timeout=0.0)
    await execution.async_start(tasks)
    state = await execution.async_close()
    return time.perf_counter() - started, state["results"]


async def run_sequential(tasks: list[dict]) -> tuple[float, list[dict]]:
    started = time.perf_counter()
    results = []
    for task in tasks:
        await asyncio.sleep(TASK_DURATIONS.get(task["id"], 0.6))
        results.append({"id": task["id"], "result": f"{task['title']} done"})
    return time.perf_counter() - started, results


async def main_async():
    provider = configure_model(temperature=0.0)
    print_model_provider(provider)

    tasks = decompose_task(
        "Build a bilingual customer-service bot that answers FAQs, checks order status, and hands off to a human agent."
    )
    independent, dependent = split_by_dependency(tasks)

    sequential_elapsed, _ = await run_sequential(independent)
    parallel_elapsed, parallel_results = await run_parallel(independent)

    summary = {
        "model_tasks": tasks,
        "independent_ids": [task["id"] for task in independent],
        "dependent_ids": [task["id"] for task in dependent],
        "parallel_result_ids": [item["id"] for item in parallel_results],
        "sequential_elapsed": round(sequential_elapsed, 3),
        "parallel_elapsed": round(parallel_elapsed, 3),
        "parallel_is_faster": parallel_elapsed < sequential_elapsed,
    }

    print("[TODO_CONCURRENCY_SUMMARY]")
    pprint(summary)

    assert set(summary["independent_ids"]) == {"t1", "t2", "t3"}
    assert set(summary["dependent_ids"]) == {"t4", "t5"}
    assert summary["parallel_is_faster"] is True


def main():
    asyncio.run(main_async())


if __name__ == "__main__":
    main()

# Expected key output with DeepSeek or local Ollama configured:
# [MODEL_PROVIDER] prints deepseek or ollama.
# [TODO_CONCURRENCY_SUMMARY] contains model_tasks generated by the model.
# independent_ids are t1, t2, t3; dependent_ids are t4, t5.
# parallel_is_faster is True.

# How it works:
# The model generates a task list with dependency metadata (task_id, title, depends_on).
# A local topological sort splits tasks into independent (no deps) and dependent groups.
# asyncio.gather() runs independent tasks in parallel; dependents run sequentially after.
# The example asserts that parallel execution is faster than serial for the independent set.
#
# Flow:
# model generates: [{id:"t1",depends_on:[]},{id:"t2",depends_on:[]},
#                   {id:"t3",depends_on:[]},{id:"t4",depends_on:["t1"]},{id:"t5",depends_on:["t2"]}]
#   |
#   v
# independent_ids = ["t1","t2","t3"]  (no dependencies)
# dependent_ids   = ["t4","t5"]       (depend on t1/t2)
#   |
#   v
# asyncio.gather(t1, t2, t3)   <- parallel
# then t4, t5 sequentially
# parallel_is_faster == True
