"""Document compliance audit — prompt-only Skill + host-side report save.

Run:
    python examples/agent_auto_orchestration/13_validate_emit_compliance_check.py

Environment:
    DEEPSEEK_API_KEY in the shell or .env file.
    Set DYNAMIC_TASK_MODEL_PROVIDER=ollama for local Ollama instead.

Scenario: legal/ops reviews a vendor services agreement for required clause
categories and compliance gaps (data handling, liability, termination, etc.).

New-standard Skills model
-------------------------
The old design used Skill ``validate`` + ``emit`` stages. Under the new standard
the Skill is pure ``SKILL.md`` guidance: ONE prompt-only request extracts
clauses, checks which required categories are present/missing, flags gaps, and
emits a risk summary (shaped by ``semantic_outputs``). The HOST writes the audit
report to disk.

Expected key output from one real DeepSeek run:
    skill status: success
    clauses_extracted>=6
    missing_or_weak categories listed
    compliant=False   (this agreement has data-handling and liability gaps)
    audit report saved: .../compliance_audit_<stamp>.md
"""

from __future__ import annotations

import asyncio
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agently import Agently
from examples.dynamic_task._shared import configure_model

# ═══════════════════════════════════════════════════════════════════════════════
# Skill definition — a standard SKILL.md, guidance only
# ═══════════════════════════════════════════════════════════════════════════════

SKILL_MD = """\
---
name: Document Compliance Audit
description: >-
  Audit a vendor agreement or contract: extract key clauses, check that required
  clause categories are present, flag compliance gaps and risks, and emit a
  structured audit summary. Use for compliance, contract review, audit, and
  vendor agreement requests.
keywords: [compliance, contract review, audit, vendor agreement, clauses]
---

# Document Compliance Audit

You are a compliance reviewer. Given a contract, produce a structured audit in
ONE pass.

## Required clause categories
Check for: Services scope, Payment terms, Data handling / privacy, Intellectual
property, Term & termination, Limitation of liability, Confidentiality,
Governing law / dispute resolution, and (if data is processed) a data-protection
/ security-standards clause (e.g. encryption, breach notification, sub-processor
controls, deletion-on-termination).

## Produce
1. Extract the key clauses present (name + one-line summary each).
2. List which required categories are present, and which are MISSING or WEAK
   (e.g. "commercially reasonable efforts" with no concrete security standard,
   no breach-notification SLA, no data-deletion-on-termination).
3. Flag each compliance gap with its risk level (low/medium/high) and why.
4. Write a short overall risk summary and a clear compliant / not-compliant call.

Be specific to the document. Do not invent clauses that are not present.
"""

VENDOR_AGREEMENT = """
VENDOR SERVICES AGREEMENT

This Vendor Services Agreement ("Agreement") is entered into as of May 15, 2026,
between AcmeTech Solutions Inc. ("Company") and DataPipe Analytics LLC ("Vendor").

1. SERVICES. Vendor shall provide real-time data processing and analytics
services as described in Exhibit A. Company grants Vendor access to Company's
production databases for the purpose of providing the Services.

2. PAYMENT. Company shall pay Vendor $18,500 per month, net 45. Late payments
shall accrue interest at 1.5% per month. Vendor may suspend services if any
invoice remains unpaid for more than 60 days.

3. DATA HANDLING. Vendor will process Company customer data including names,
email addresses, purchase history, and device identifiers. Vendor shall use
commercially reasonable efforts to protect such data. Vendor may use aggregated
and anonymized data for product improvement and benchmarking.

4. INTELLECTUAL PROPERTY. Any algorithms, models, or software developed by
Vendor in the course of providing the Services shall remain the sole property
of Vendor. Company retains ownership of its data and any derivative reports
generated by the Services.

5. TERM AND TERMINATION. This Agreement commences on the Effective Date and
continues for 12 months. Either party may terminate with 30 days written notice.
In the event of material breach, the non-breaching party may terminate
immediately upon written notice.

6. LIMITATION OF LIABILITY. VENDOR'S TOTAL LIABILITY UNDER THIS AGREEMENT SHALL
NOT EXCEED THE FEES PAID BY COMPANY IN THE 3 MONTHS PRECEDING THE CLAIM. IN NO
EVENT SHALL VENDOR BE LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES.

7. CONFIDENTIALITY. Each party agrees to maintain the confidentiality of the
other party's proprietary information. "Proprietary Information" does not
include information that is or becomes publicly available through no fault of
the receiving party.

8. GOVERNING LAW. This Agreement shall be governed by the laws of the State of
Delaware. Any disputes shall be resolved through binding arbitration in
Wilmington, Delaware.
"""


def install_skill() -> str:
    skill_src = Path(tempfile.mkdtemp(prefix="agently_skill_src_")) / "document-compliance-audit"
    skill_src.mkdir(parents=True, exist_ok=True)
    (skill_src / "SKILL.md").write_text(SKILL_MD, encoding="utf-8")
    Agently.settings.set("skills.registry.root", tempfile.mkdtemp(prefix="agently_skills_reg_"))
    Agently.settings._set_item_by_dot_path("skills.allowed_trust_levels", ["local"], cover=True)
    contract = Agently.skills_executor.install_skills(skill_src, trust_level="local", update=True)
    return str(contract["skill_id"])


def save_audit(reports_dir: Path, risk_summary: str, body: str) -> Path:
    reports_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = reports_dir / f"compliance_audit_{stamp}.md"
    path.write_text(f"# Compliance Audit\n\n## Risk Summary\n\n{risk_summary}\n\n{body}\n", encoding="utf-8")
    return path


async def main() -> None:
    provider = configure_model(temperature=0.2)
    print(f"Model provider: {provider}\n")

    skill_id = install_skill()
    agent = Agently.create_agent("compliance-auditor")

    divider = "=" * 60
    print(divider)
    print("Document Compliance Audit — prompt-only Skill")
    print(divider)
    print("Auditing vendor services agreement...\n")

    streamed: set[str] = set()

    async def on_stream(item: dict[str, Any]) -> None:
        if item.get("type") != "skills.model_stream":
            return
        path = item.get("path")
        if path and item.get("is_complete") and path not in streamed:
            streamed.add(str(path))
            print(f"  [section ready] {path}")

    execution = await agent.async_run_skills_task(
        f"Audit this vendor agreement for compliance:\n\n{VENDOR_AGREEMENT}",
        skills=[skill_id],
        mode="required",
        semantic_outputs={
            "clauses": (
                [{"name": (str, "Clause name", True), "summary": (str, "One-line summary", True)}],
                "Key clauses present in the document",
                True,
            ),
            "present_categories": ([str], "Required categories that are present", True),
            "missing_or_weak_categories": ([str], "Required categories missing or weak", True),
            "gaps": (
                [{
                    "category": (str, "Category", True),
                    "risk": (str, "Risk level: low, medium, high", True),
                    "why": (str, "Why this is a compliance gap", True),
                }],
                "Compliance gaps with risk levels",
                True,
            ),
            "risk_summary": (str, "Short overall risk summary", True),
            "compliant": (bool, "True only if no high-risk gaps remain", True),
        },
        stream_handler=on_stream,
    )

    print(f"\nskill status: {execution.status}")
    if execution.status != "success":
        print("output:", execution.output)
        return

    result = execution.output or {}
    clauses = result.get("clauses", []) or []
    gaps = result.get("gaps", []) or []
    missing = result.get("missing_or_weak_categories", []) or []

    print(f"\n  clauses extracted: {len(clauses)}")
    print(f"  missing/weak categories: {', '.join(str(m) for m in missing) or '—'}")
    print(f"  gaps: {len(gaps)}")
    for g in gaps[:4]:
        print(f"    · [{g.get('risk', '—')}] {g.get('category', '—')}: {str(g.get('why', ''))[:80]}")
    print(f"\n[Risk summary]\n{str(result.get('risk_summary', '—'))[:400]}")

    body = "\n".join(f"- [{g.get('risk')}] {g.get('category')}: {g.get('why')}" for g in gaps)
    out_path = save_audit(Path(tempfile.mkdtemp(prefix="agently_compliance_")), str(result.get("risk_summary", "")), body)

    print(f"\nskill status: {execution.status}")
    print(f"clauses_extracted={len(clauses)}")
    print(f"compliant={bool(result.get('compliant'))}")
    print(f"audit report saved: {out_path}")


if __name__ == "__main__":
    asyncio.run(main())
